id: IC44CB44A
legacy_id: P010785
ocr_import_info:
  bdrc_scan_id: W1KG8579
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T22:41:48'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T08:20:24.090765+00:00'
last_modified: 2022-08-27 16:21:49.326022
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG8579
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG8579
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕར་ཕྱིན་སྤྱི་མཐའ་བཟུང་འབྲེལ།
  author: ཅོ་ནེ་གྲགས་པ་བཤད་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9667609434519181
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG8592:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8592
      total_pages: 506
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG8592.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9639824263924291
    legacy_id: v002
  I1KG8591:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8591
      total_pages: 364
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8591.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9707720480509588
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
