id: IC44CB44A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T22:45:07+00:00'
last_modified: '2022-06-08T17:30:34.880376+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8579
  title: ཕར་ཕྱིན་སྤྱི་མཐའ་བཟུང་འབྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F8B9:
      image_group_id: I1KG8591
      title: ''
      total_pages: 364
      order: 1
      base_file: F8B9.txt
    BF19:
      image_group_id: I1KG8592
      title: ''
      total_pages: 506
      order: 2
      base_file: BF19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
