id: P010785
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-20 10:24:25.404994
source_metadata:
  id: bdr:W1KG8579
  title: ཕར་ཕྱིན་སྤྱི་མཐའ་བཟུང་འབྲེལ།
  author: ''
  volumes:
    f7bc413b6b8e40c28f9544fbc2fa58e0:
      image_group_id: I1KG8591
      title: ''
      volume_number: 1
      total_pages: 364
      base_file: v001.txt
    e65c2230d1e54cb7a8fe6cc6c88d5c6e:
      image_group_id: I1KG8592
      title: ''
      volume_number: 2
      total_pages: 506
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
